---
title: "hw5_mx2286"
author: "William Xie"
date: "2024-11-15"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
library(broom)
library(purrr)
library(dplyr)
library(tidyr)
```
## Problem2
```{r 2-1: save ðœ‡Ì‚ and the p-value}
set.seed(1)
sim_p_true = function(true_mean){
  data = rnorm(30, mean = true_mean, sd = 5)
  test = t.test(data, mu=0)
  result = broom::tidy(test)
  result_df = result %>% 
    dplyr::select(mu_hat = estimate, p_value = p.value) 
  return (result_df)
}

test_results = expand_grid(
  true_mean = 0:6,
  iter = 1:5000
) %>% 
  mutate(simulation = map(true_mean, sim_p_true)) %>%
  unnest(simulation) %>% 
  mutate(indicator = as.numeric(p_value < 0.05))
```

```{r 2-2: plot showing the proportion of times the null was rejected}

power_results = test_results %>%
  group_by(true_mean) %>%
  summarize(power = mean(p_value < 0.05))

ggplot(power_results, aes(x = true_mean, y = power)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Proportion of times the null was rejected ",
    x = "true mean (effect size)",
    y = "power"
  ) +
  theme_minimal()
```
Comment: From the graph, we can see that the power increases as true mean increases and eventually be closer to 1. As the effect size increases, the power would increase.
